import React, { useState } from "react";
import { Link } from "react-router-dom";
import PageOne from "pages/PageOne";
import PageTwo from "pages/PageTwo";
import PageThree from "pages/PageThree";
import PageFour from "pages/PageFour";
import PageFive from "pages/PageFive";
const Home = () => {

  const [currentPage, setCurrentPage] = useState(0);
  const pages = [
    <PageOne/>,
    <PageTwo/>,
    <PageThree/>,
    <PageFour/>,
    <PageFive/>,
  ];

  const handleWheel = (e) => {
    // todo
    // 加个防抖或节流
    if (e.deltaY > 0 && currentPage < pages.length - 1) {
      setCurrentPage(currentPage + 1);
    } else if (e.deltaY < 0 && currentPage > 0) {
      setCurrentPage(currentPage - 1);
    }
  };

  return (
    <div onWheel={handleWheel} className="fixed inset-0 overflow-hidden">
      <div className="transition-transform duration-500 ease-in-out" style={{ transform: `translateY(-${currentPage * 100}vh)` }}>
        {pages.map((page, index) => (
          <div key={index} className="w-full h-screen flex justify-center items-center text-4xl">
            {page}
          </div>
        ))}
      </div>
    </div>
  );
/*

  const [currentPage, setCurrentPage] = useState(0);
  const numPages = 3;

  const handleWheel = (e) => {
    if (e.deltaY > 0 && currentPage < numPages - 1) {
      setCurrentPage(currentPage + 1);
    } else if (e.deltaY < 0 && currentPage > 0) {
      setCurrentPage(currentPage - 1);
    }
  };

  return (
    <div onWheel={handleWheel} className="fixed inset-0 overflow-hidden">
      <div className="transition-transform duration-500 ease-in-out" style={{ transform: `translateY(-${currentPage * 100}vh)` }}>
        <div className="w-full h-screen flex justify-center items-center bg-red-500 text-white text-4xl">Page 1</div>
        <div className="w-full h-screen flex justify-center items-center bg-blue-500 text-white text-4xl">Page 2</div>
        <div className="w-full h-screen flex justify-center items-center bg-green-500 text-white text-4xl">Page 3</div>
      </div>
    </div>
  );
*/


  // return (
  //   <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
  //     <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
  //     <p style={{ fontSize: "18px", marginBottom: "30px" }}>
  //       This project was generated By{" "}
  //       <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
  //         Dhiwise
  //       </a>
  //       . Quickly use below links to navigate through all pages.
  //     </p>
  //
  //   </div>
  // );
};
export default Home;
